name: tests

on:
  - push
  - pull_request

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup Pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: pip-${{ hashFiles('.github/**/*.yaml') }}
      - name: Setup Poetry Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Pytest
        run: |
          poetry run pytest -v
